In [1]:
# Importamos librerias necesarias
import pandas as pd
import os

# Acceder a la ruta donde se encuentra los archivos
ruta = os.getcwd()

# Leemos el archivo .csv
df = pd.read_csv(ruta+r"\nba_data_final.csv")

In [2]:
# Realizamos una lectura de los primeros 2 registros del dataset
df.head(2)

,name,games_played,minutes_played,points_scored,goals_scored,goals_attempted,3_point_scored,3_point_attempted,free_throws_scored,free_throws_attempted,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnover,5yrs
0,Brandon Ingram,36.0,27.4,7.4,2.6,7.6,0.5,2.1,1.6,2.3,0.7,3.4,1.9,0.4,0.4,1.3,0.0
1,Andrew Harrison,35.0,26.9,7.2,2.0,6.7,0.7,2.8,2.6,3.4,0.5,2.0,3.7,1.1,0.5,1.6,0.0

In [22]:
print("Cantidad de registros y columnas:")
print(df.shape)

Cantidad de registros y columnas:
(2672, 17)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2672 entries, 0 to 2671
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   2671 non-null   object
 1   games_played           2671 non-null   float64
 2   minutes_played         2671 non-null   float64
 3   points_scored          2671 non-null   float64
 4   goals_scored           2671 non-null   float64
 5   goals_attempted        2671 non-null   float64
 6   3_point_scored         1970 non-null   float64
 7   3_point_attempted      1970 non-null   float64
 8   free_throws_scored     2671 non-null   float64
 9   free_throws_attempted  2671 non-null   float64
 10  offensive_rebounds     2214 non-null   float64
 11  defensive_rebounds     2214 non-null   float64
 12  assists                2671 non-null   float64
 13  steals                 2214 non-null   float64
 14  blocks                 2214 non-null   float64
 15  turnover               2040 non-null   float64
 16  5yrs                   2671 non-null   float64
dtypes: float64(16), object(1)
memory usage: 355.0+ KB

In [24]:
df.columns

Index(['name', 'games_played', 'minutes_played', 'points_scored',
       'goals_scored', 'goals_attempted', '3_point_scored',
       '3_point_attempted', 'free_throws_scored', 'free_throws_attempted',
       'offensive_rebounds', 'defensive_rebounds', 'assists', 'steals',
       'blocks', 'turnover', '5yrs'],
      dtype='object')

In [25]:
df = df.drop(["goals_attempted", "3_point_attempted",
               "free_throws_attempted", "defensive_rebounds", "5yrs"
               ], axis = 1).set_axis(['NOMBRE', 'PARTIDOS_JUGADOS',
                  'MINUTOS_JUGADOS_PROMEDIO', 'PUNTOS_ANOTADOS_PROMEDIO', 'GOLES_PROMEDIO',
                  'TRIPLES_PROMEDIO', 'TIROS_LIBRES_ANOTADOS_PROMEDIO', 'REBOTES_OFENSIVOS_PROMEDIO',
                  'ASISTENCIAS_PROMEDIO', 'PELOTAS_RECUPERADAS_PROMEDIO', 'BLOQUEOS_PROMEDIO', "PERDIDAS_PROMEDIO"], axis=1)
df.head(2)

,NOMBRE,PARTIDOS_JUGADOS,MINUTOS_JUGADOS_PROMEDIO,PUNTOS_ANOTADOS_PROMEDIO,GOLES_PROMEDIO,TRIPLES_PROMEDIO,TIROS_LIBRES_ANOTADOS_PROMEDIO,REBOTES_OFENSIVOS_PROMEDIO,ASISTENCIAS_PROMEDIO,PELOTAS_RECUPERADAS_PROMEDIO,BLOQUEOS_PROMEDIO,PERDIDAS_PROMEDIO
0,Brandon Ingram,36.0,27.4,7.4,2.6,0.5,1.6,0.7,1.9,0.4,0.4,1.3
1,Andrew Harrison,35.0,26.9,7.2,2.0,0.7,2.6,0.5,3.7,1.1,0.5,1.6

In [26]:
df.describe()

,PARTIDOS_JUGADOS,MINUTOS_JUGADOS_PROMEDIO,PUNTOS_ANOTADOS_PROMEDIO,GOLES_PROMEDIO,TRIPLES_PROMEDIO,TIROS_LIBRES_ANOTADOS_PROMEDIO,REBOTES_OFENSIVOS_PROMEDIO,ASISTENCIAS_PROMEDIO,PELOTAS_RECUPERADAS_PROMEDIO,BLOQUEOS_PROMEDIO,PERDIDAS_PROMEDIO
count,2671.000000,2671.000000,2671.000000,2671.000000,1970.000000,2671.000000,2214.000000,2671.000000,2214.000000,2214.000000,2040.000000
mean,61.390865,17.927892,7.024448,2.723512,0.283198,1.370236,1.030533,1.534070,0.625023,0.391554,1.176471
std,16.716561,8.422515,4.601011,1.785711,0.414377,1.082123,0.796886,1.388457,0.423792,0.473191,0.723795
min,11.000000,3.100000,0.700000,0.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,11.200000,3.800000,1.500000,0.000000,0.700000,0.400000,0.600000,0.300000,0.100000,0.700000
50%,64.000000,16.400000,5.700000,2.200000,0.100000,1.100000,0.800000,1.100000,0.500000,0.200000,1.000000
75%,77.000000,23.350000,9.000000,3.500000,0.400000,1.800000,1.400000,2.000000,0.800000,0.500000,1.500000
max,83.000000,46.400000,37.600000,14.800000,2.400000,9.200000,5.400000,10.600000,3.500000,5.000000,4.400000

In [27]:
df.isnull().sum()

NOMBRE                              1
PARTIDOS_JUGADOS                    1
MINUTOS_JUGADOS_PROMEDIO            1
PUNTOS_ANOTADOS_PROMEDIO            1
GOLES_PROMEDIO                      1
TRIPLES_PROMEDIO                  702
TIROS_LIBRES_ANOTADOS_PROMEDIO      1
REBOTES_OFENSIVOS_PROMEDIO        458
ASISTENCIAS_PROMEDIO                1
PELOTAS_RECUPERADAS_PROMEDIO      458
BLOQUEOS_PROMEDIO                 458
PERDIDAS_PROMEDIO                 632
dtype: int64

In [28]:
data = df.dropna(subset=["NOMBRE"])

In [29]:
data.isnull().sum()

NOMBRE                              0
PARTIDOS_JUGADOS                    0
MINUTOS_JUGADOS_PROMEDIO            0
PUNTOS_ANOTADOS_PROMEDIO            0
GOLES_PROMEDIO                      0
TRIPLES_PROMEDIO                  701
TIROS_LIBRES_ANOTADOS_PROMEDIO      0
REBOTES_OFENSIVOS_PROMEDIO        457
ASISTENCIAS_PROMEDIO                0
PELOTAS_RECUPERADAS_PROMEDIO      457
BLOQUEOS_PROMEDIO                 457
PERDIDAS_PROMEDIO                 631
dtype: int64

In [30]:
# Se remplazan los valores nulos por 0
data = data.fillna(0)

In [31]:
data.isnull().sum()

NOMBRE                            0
PARTIDOS_JUGADOS                  0
MINUTOS_JUGADOS_PROMEDIO          0
PUNTOS_ANOTADOS_PROMEDIO          0
GOLES_PROMEDIO                    0
TRIPLES_PROMEDIO                  0
TIROS_LIBRES_ANOTADOS_PROMEDIO    0
REBOTES_OFENSIVOS_PROMEDIO        0
ASISTENCIAS_PROMEDIO              0
PELOTAS_RECUPERADAS_PROMEDIO      0
BLOQUEOS_PROMEDIO                 0
PERDIDAS_PROMEDIO                 0
dtype: int64

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2671 entries, 0 to 2671
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NOMBRE                          2671 non-null   object
 1   PARTIDOS_JUGADOS                2671 non-null   float64
 2   MINUTOS_JUGADOS_PROMEDIO        2671 non-null   float64
 3   PUNTOS_ANOTADOS_PROMEDIO        2671 non-null   float64
 4   GOLES_PROMEDIO                  2671 non-null   float64
 5   TRIPLES_PROMEDIO                2671 non-null   float64
 6   TIROS_LIBRES_ANOTADOS_PROMEDIO  2671 non-null   float64
 7   REBOTES_OFENSIVOS_PROMEDIO      2671 non-null   float64
 8   ASISTENCIAS_PROMEDIO            2671 non-null   float64
 9   PELOTAS_RECUPERADAS_PROMEDIO    2671 non-null   float64
 10  BLOQUEOS_PROMEDIO               2671 non-null   float64
 11  PERDIDAS_PROMEDIO               2671 non-null   float64
dtypes: float64(11), object(1)
memory usage: 271.3+ KB

In [36]:
# Generar el ID único utilizando un contador
id_prefix = "ID_JUG_"
id_counter = 1

def generate_unique_id():
    global id_counter
    unique_id = f"{id_prefix}{id_counter:04d}"
    id_counter += 1
    return unique_id

# Agregar una nueva columna "ID" al DataFrame con los IDs únicos generados
data['ID_JUGADOR'] = data.apply(lambda row: generate_unique_id(), axis=1)

In [38]:
# Nombre de la columna que deseas mover al principio
columna_a_mover = 'ID_JUGADOR'

# Obtener el índice de la columna que deseas mover
indice_columna = data.columns.get_loc(columna_a_mover)

# Mover la columna al principio del DataFrame
data.insert(0, columna_a_mover, data.pop(columna_a_mover))

data.head()

,ID_JUGADOR,NOMBRE,PARTIDOS_JUGADOS,MINUTOS_JUGADOS_PROMEDIO,PUNTOS_ANOTADOS_PROMEDIO,GOLES_PROMEDIO,TRIPLES_PROMEDIO,TIROS_LIBRES_ANOTADOS_PROMEDIO,REBOTES_OFENSIVOS_PROMEDIO,ASISTENCIAS_PROMEDIO,PELOTAS_RECUPERADAS_PROMEDIO,BLOQUEOS_PROMEDIO,PERDIDAS_PROMEDIO
0,ID_JUG_0001,Brandon Ingram,36.0,27.4,7.4,2.6,0.5,1.6,0.7,1.9,0.4,0.4,1.3
1,ID_JUG_0002,Andrew Harrison,35.0,26.9,7.2,2.0,0.7,2.6,0.5,3.7,1.1,0.5,1.6
2,ID_JUG_0003,JaKarr Sampson,74.0,15.3,5.2,2.0,0.4,0.9,0.5,1.0,0.5,0.3,1.0
3,ID_JUG_0004,Malik Sealy,58.0,11.6,5.7,2.3,0.1,0.9,1.0,0.8,0.6,0.1,1.0
4,ID_JUG_0005,Matt Geiger,48.0,11.5,4.5,1.6,0.0,1.3,1.0,0.3,0.3,0.4,0.8

In [39]:
# Exportamos los datos finales
data.to_excel("Jugadores NBA.xlsx", encoding="utf-8", index=False)
data.to_csv("Jugadores NBA.csv", encoding="utf-8", index=False)